base_link_to_laser:
  ros__parameters:
    # Translations (x, y, z) in meters
    translation:
      x: 0.0
      y: 0.0
      z: 0.2
    
    # Rotations (roll, pitch, yaw) in radians
    rotation:
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
    
    # Frame IDs
    frame_id: "base_link"
    child_frame_id: "laser"
